import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Navbar } from "@/components/Navbar";
import { PainelButton } from "@/components/PainelButton"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chamada Aula de Violão",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
        <PainelButton />
      </body>
    </html>
  );
}
